export const TRACECHART_API_SUCCESS = "TRACECHART_API_SUCCESS";
export const TRACECHART_API_FAILURE = "TRACECHART_API_FAILURE";
export const TRACECHART_API_LOADING = "TRACECHART_API_LOADING";
export const TRACECHART_API_PIPELINE = "TRACECHART_API_PIPELINE";
export const TRACECHART_API_RESET = "TRACECHART_API_RESET";
export const TRACECHART_API_SUCCESS_TOUCH = "TRACECHART_API_SUCCESS_TOUCH";