export const TRACEABILITY_API_SUCCESS = "TRACEABILITY_API_SUCCESS";
export const TRACEABILITY_API_FAILURE = "TRACEABILITY_API_FAILURE";
export const TRACEABILITY_API_LOADING = "TRACEABILITY_API_LOADING";
export const TRACEABILITY_API_RESET = "TRACEABILITY_API_RESET";