export const API_OVERVIEW_SUCCESS = "API_OVERVIEW_SUCCESS";
export const API_OVERVIEW_FAILURE = "API_OVERVIEW_SUCCESS";
export const API_OVERVIEW_LOADING = "API_OVERVIEW_LOADING";
export const API_OVERVIEW_PIPELINE = "API_OVERVIEW_PIPELINE";
export const API_OVERVIEW_SEARCH = "API_OVERVIEW_SEARCH";