export const AUDIT_API_SUCCESS = "AUDIT_API_SUCCESS";
export const AUDIT_API_FAILURE = "AUDIT_API_FAILURE";
export const AUDIT_API_LOADING = "AUDIT_API_LOADING";
export const AUDIT_FILTER_API_SUCCESS = "AUDIT_FILTER_API_SUCCESS";
export const AUDIT_FILTER_API_FAILURE = "AUDIT_FILTER_API_FAILURE";
export const AUDIT_FILTER_API_LOADING = "AUDIT_FILTER_API_LOADING";
export const AUDIT_RESET_API_RECORD = "AUDIT_RESET_API_RECORD";