export const ANAMOLY_API_SUCCESS = "ANAMOLY_API_SUCCESS";
export const ANAMOLY_API_FAILURE = "ANAMOLY_API_FAILURE";
export const ANAMOLY_API_LOADING = "ANAMOLY_API_LOADING";
export const ANAMOLY_API_SEARCH = "ANAMOLY_API_SEARCH";
export const ANAMOLY_SORT = "ANAMOLY_SORT";
export const ANAMOLY_API_SUCCESS_INITIAL = "ANAMOLY_API_SUCCESS_INITIAL";
export const ANAMOLY_API_LOADING_INITIAL = "ANAMOLY_API_LOADING_INITIAL";