export default {
    EXPECTATION_LIST_REQUEST : "EXPECTATION_LIST_REQUEST",
    EXPECTATION_LIST_SUCCESS : "EXPECTATION_LIST_SUCCESS",
    EXPECTATION_LIST_FAILURE : "EXPECTATION_LIST_FAILURE",
    PIPELINE_HISTORY_LIST_REQUEST : "PIPELINE_HISTORY_LIST_REQUEST",
    PIPELINE_HISTORY_LIST_SUCCESS : "PIPELINE_HISTORY_LIST_SUCCESS",
    PIPELINE_HISTORY_LIST_FAILURE : "PIPELINE_HISTORY_LIST_FAILURE",
    PIPELINE_HISTORY_LIST_ADD : "PIPELINE_HISTORY_LIST_ADD"
}